version: '3'

services:

  server2:
    image: 'elproyectegrande.azurecr.io/openjdk:17-jdk-alpine'
    build: ./backend
    container_name: server2
    ports:
      - 8080:8080
    depends_on:
      - db5
    environment:
      - SPRING_DATASOURCE_URL=${DBURL}
      - SPRING_DATASOURCE_USERNAME=${USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  client2:
    image: elproyectegrande.azurecr.io/node:alpine3.12
    build: ./frontend
    container_name: client2
    environment:
      - CLIENT_PORT=${CLIENT_PORT}
    expose:
      - ${CLIENT_PORT}
    ports:
    - ${CLIENT_PORT}:${CLIENT_PORT}
    links:
      - server2
    command: npm start
          
  db5:
    image: 'postgres:13-alpine'
    container_name: aibest5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${USERNAME}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=aibest5
